[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
rust-version = "1.79"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Jean Marchand"]
repository = "https://github.com/rust-lang/rust-analyzer"

[workspace.dependencies]
aligned = "0.4.2"
anchor-lang-idl-spec = "0.1.0"
bytemuck = "1.19"
cargo-manifest = "0.16"
typhoon-accounts = { version = "0.1.0", path = "crates/accounts" }
typhoon-account-macro = { version = "0.1.0", path = "crates/account-macro" }
typhoon-context = { version = "0.1.0", path = "crates/context" }
typhoon-context-macro = { version = "0.1.0", path = "crates/context-macro" }
typhoon-errors = { version = "0.1.0", path = "crates/errors" }
typhoon-handler-macro = { version = "0.1.0", path = "crates/handler-macro" }
typhoon-metadata-extractor = { version = "0.1.0", path = "crates/metadata-extractor" }
typhoon-program = { version = "0.1.0", path = "crates/program" }
typhoon-program-id-macro = { version = "0.1.0", path = "crates/program-id-macro" }
typhoon-space = { version = "0.1.0", path = "crates/space" }
typhoon-space-macro = { version = "0.1.0", path = "crates/space-macro" }
typhoon-syn = { version = "0.1.0", path = "crates/syn" }
typhoon-traits = { version = "0.1.0", path = "crates/traits" }
heck = "0.5.0"
litesvm = "0.3.0"
nostd-system-program = { git = "https://github.com/Aursen/nostdinfo-programs" }
num-traits = "0.2"
paste = "1.0"
pinocchio = { git = "https://github.com/febo/pinocchio" }
pinocchio-pubkey = { git = "https://github.com/febo/pinocchio" }
pinocchio-system = { git = "https://github.com/febo/pinocchio" }
proc-macro2 = "1.0"
quote = "1.0"
solana-nostd-entrypoint = { git = "https://github.com/cavemanloverboy/solana-nostd-entrypoint" }
solana-program = "1.18"
solana-sdk = "2.0"
syn = "2.0"
thiserror = "1.0"
