[package]
name = "lever"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
logging = []

[lints]
workspace = true

[dependencies]
bytemuck.workspace = true
typhoon.workspace = true
lever-interface.workspace = true
