[env]
CARGO_MAKE_WORKSPACE_EMULATION = true

CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
    "anchor-cpi",
    "counter",
    "hello-world",
    "instruction-data",
    "seeded",
    "seeds",
    "transfer-sol",
    "transfer-token",
]
