[package]
name = "hand"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
logging = []

[lints]
workspace = true

[dependencies]
bytemuck.workspace = true
hand-interface.workspace = true
lever-interface = { workspace = true, features = ["cpi"] }
typhoon.workspace = true
